version: "3.9"
services:
  getting-started-with-sw:
    image: "com.thegreatapi/greeting-flow:1.0"
    ports:
      - "8080:8080"
  translation-service:
    image: "com.thegreatapi/translation-service:1.0"
    ports:
      - "8081:8081"