version: "3.9"
services:
  getting-started-with-sw:
    image: "com.acme/greeting-flow:1.0"
    ports:
      - "8080:8080"
    environment:
      - kogito.sw.functions.getGreetingFunction.host=international-greeting-service
  international-greeting-service:
    image: "com.acme/international-greeting-service:1.0"
    ports:
      - "8081:8081"