version: "3.9"
services:
  getting-started-with-sw:
    image: "com.acme/greeting-flow:1.0"
    ports:
      - "8080:8080"
    environment:
      # Defines the base URL for the international-greeting-service.
      # "openapi" is the sanitized filename of the OpenAPI document.
      - org.kogito.openapi.client.openapi.base_path=http://international-greeting-service:8081
  international-greeting-service:
    image: "com.acme/international-greeting-service:1.0"
    ports:
      - "8081:8081"