---
openapi: 3.0.3
info:
  title: translation-service API
  version: '1.0'
servers:
# Use localhost when running locally (quarkus dev)
#  - url: http://localhost:8081/

# Use translation-service when running with docker-compose
#  - url: http://translation-service:8081/

  - url: http://translation-service:8081/
paths:
  /translate:
    post:
      tags:
      - Translate Resource
      operationId: translate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Data:
      type: object
      properties:
        language:
          type: string
        name:
          type: string
